//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFI_ControlCalidadEntities : DbContext
    {
        public TFI_ControlCalidadEntities()
            : base("name=TFI_ControlCalidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Defecto> Defecto { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Hallazgo> Hallazgo { get; set; }
        public virtual DbSet<Orden_Produccion> Orden_Produccion { get; set; }
        public virtual DbSet<JornadaLaboral> JornadaLaboral { get; set; }
    }
}
