//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hallazgo
    {
        public int ID_Hallazgo { get; set; }
        public Nullable<System.DateTime> Fecha_Hallazgo { get; set; }
        public Nullable<System.TimeSpan> Hora_Registro { get; set; }
        public string Pie { get; set; }
        public Nullable<int> Defecto_id { get; set; }
        public Nullable<int> ID_JL { get; set; }
    
        public virtual Defecto Defecto { get; set; }
        public virtual JornadaLaboral JornadaLaboral { get; set; }
    }
}
