//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modelo()
        {
            this.Color = new HashSet<Color>();
            this.Orden_Produccion = new HashSet<Orden_Produccion>();
        }
    
        public int SKU { get; set; }
        public string Denominacion { get; set; }
        public Nullable<int> LimiteSuperiorObs { get; set; }
        public Nullable<int> LimiteInferiorObs { get; set; }
        public Nullable<int> LimiteSuperiorRep { get; set; }
        public Nullable<int> LimiteInferiorRep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Color> Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Produccion> Orden_Produccion { get; set; }
    }
}
