//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Produccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden_Produccion()
        {
            this.JornadaLaboral = new HashSet<JornadaLaboral>();
        }
    
        public int Numero_OP { get; set; }
        public Nullable<System.DateTime> Fecha_I { get; set; }
        public Nullable<System.DateTime> Fecha_F { get; set; }
        public Nullable<int> num_linea { get; set; }
        public string Estado { get; set; }
        public Nullable<int> codigo_color { get; set; }
        public Nullable<int> sku_modelo { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JornadaLaboral> JornadaLaboral { get; set; }
    }
}
